export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export JRE_HOME=$JAVA_HOME/jre
export CLASSPATH=.:$CLASSPATH:$JAVA_HOME/lib:$JAVA_HOME/jre/lib:$JAVA_HOME/lib/tools.jar:/$JAVA_HOME/lib/dt.jar
export PATH=$PATH:$JAVA_HOME/bin:$JAVA_HOME/jre/bin
